MapColonies/pycsw

- constants.py
- docker/entrypoint.py
- docs/profiles.rst
- etc/mappings.py
- pycsw/core/admin.py
- pycsw/plugins/profiles/base_profile/base_profile.py
- pycsw/plugins/profiles/base_profile/docs/base_profile.rst
- pycsw/plugins/profiles/base_profile/models/models.py
Adds a base class for profiles that already implements the needed functions for record writing
#1
> Add profile base

- etc/mappings.py
- pycsw/plugins/profiles/mc_raster/mc_raster.py
- pycsw/plugins/profiles/mc_raster/schemas/mcraster-record.xsd
> chore: added polygon parts field

- pycsw/plugins/profiles/mc_dem/mc_dem.py
- pycsw/plugins/profiles/mc_dem/schemas/mcrdem-record.xsd
> feat: dem 3fields profile

- pycsw/plugins/profiles/profile.py
> fix: revert print

- pycsw/plugins/profiles/base_profile/base_profile.py
link format CSW compliency 
**name , description , protocol , url**
> fix: link csw compliency

- .gitattributes
- .licrc
- docker/entrypoint.py
- pycsw/cors.py
- requirements.txt
> feat: added cors support

- docker/entrypoint.py
> feat:  added env for gunicorn log format

- Dockerfile
- docker/pycsw.cfg
- docker/uwsgi-start.sh
- requirements.txt
- uwsgi.ini
> chore: add uwsgi to pycsw

- pycsw/plugins/profiles/mc3d/mc3d.py
Add update date field.
No related issue.
No additional information.
> feat: add update date

- helm/raster/config/mappings.py
- pycsw/plugins/profiles/mc_raster/mc_raster.py
adding transparency record for mc-raster
> feat!: adding transparency format

- requirements.txt
> fix: geolinks version

- pycsw/plugins/profiles/mc_dem/mc_dem.py
> fix: schema file name

- helm/raster/config/jwt.js
- helm/raster/config/nginx.conf
- helm/raster/config/nginx_root.conf
- helm/raster/templates/nginx-configmap.yaml
- helm/raster/templates/nginx-deployment.yaml
> added token user details from payload (MAPCO-3062)

- helm/raster/config/nginx.conf
> fix: uwsgi cookie header handler

- helm/raster/templates/configmap.yaml
> chore: added PGAPPNAME environment variable to raster configmap (MAPCO-3796)

- helm/raster/Chart.yaml
> fix: chart version

- helm/raster/Chart.yaml
- helm/raster/templates/envoy/opa-secret.yaml
- helm/raster/values.yaml
> fix: added opa secret condition

- helm/raster/Chart.yaml
- helm/raster/templates/configmap.yaml
- helm/raster/values.yaml
[# Related Issue / Discussion]
(https://mapcolonies.atlassian.net/browse/MAPCO-3954)
> fix: Add coordinate precision support to raster (MAPCO-3954)

- helm/raster/Chart.yaml
- helm/raster/config/mappings.py
- pycsw/plugins/profiles/mc_raster/mc_raster.py
* support the tileMimeFormat field.
* raster profile
* tileFormat attribute will retrive from tile_mime_format column on catalog db
> feat: Raster-tile-mime-format (MAPCO-3257)

- .github/workflows/build_and_push.yaml
- helm/raster/config/mappings.py
- pycsw/plugins/profiles/mc_raster/mc_raster.py
According to product  requirements:
imageFormat changed to "tileFormat" to represent the image mime type.
=================================
Also added upgrade to git action so it will also auto publish helm registry version on releasing
> fix: Change-imageFormat-mimeType

- helm/raster/templates/_helpers.tpl
- helm/raster/templates/deployment.yaml
> fix: fix url from localhost

- helm/raster/Chart.yaml
> chore: helm version before release

- helm/raster/templates/_helpers.tpl
- helm/raster/values.yaml
Fixed an issue that prevented the helm to be installable
> fix: raster route server url

- helm/raster/Chart.yaml
Helm charts version upgraded to 6.0.1.
> helm: chart version upgraded to 6.0.1

- helm/3d/config/pycsw.cfg
- helm/3d/values.yaml
> feat: 3D set default max-records to 50 and fix filterProductStatus filter (MAPCO-8216)

- .github/workflows/build-and-push.yaml
> ci: fix docker location in ci process (MAPCO-8513)

- helm/3d/values.yaml
> fix: 3D helm Set default cors behavior (MAPCO-8526)
